admincu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('', front, name='front'),
    path('el_json_para_huevo/<int:pk>/' , el_json_para_huevo, name='el_json_para_huevo' ),
    path('admincudj/', admin.site.urls),
    path('recuperar-pass/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('mercadopago/', include(('django_mercadopago.urls', 'mercadopago'), namespace='mp')),
    path('terms/', include('termsandconditions.urls')),
    path('maintenance-mode/', include('maintenance_mode.urls')),
    path('home', home, name='home'),
    path('biblioteca/', include('biblioteca.urls')),
    path('perfil/', include('perfil.urls')),
    path('mantenimiento/', mantenimiento, name='mantenimiento'),
    path('parametros/', include('arquitectura.urls')),
    path('facturacion/', include('creditos.urls')),
    path('cobranzas/', include('comprobantes.urls')),
    path('deudas/', include('op.urls_deudas')),
    path('pagos/', include('op.urls_pagos')),
    path('administracion/', include('contabilidad.urlsadmin')),
    path('contabilidad/', include('contabilidad.urls')),
    path('reportes/', include('reportes.urls')),
    path('resumenes/', include('resumenes.urls')),
    path('socio/', include(('socio.urls', 'socio'), namespace='socio')),
    path('superusuario/', include('consorcios.urls')),
    path('herramientas/', include('herramientas.urls')),
    path('api/', include('api.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
	EstadoCuentaViewSet
)

router = DefaultRouter()
router.register(r'estado_cuenta', EstadoCuentaViewSet, basename='api')

urlpatterns = [
	path('', include(router.urls))
]

contabilidad/cuentas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', pc_index, name='cuentas'),
	path('nuevo/', pc_nuevo, name='cuentas_nuevo'),
	path('desvincular/<str:cuenta>/', pc_desvincular, name='cuentas_desvincular'),
	path('<str:cuenta>/', pc_set, name='cuentas_set'),
]

contabilidad/urls.py
from django.urls import include, path
from .views import *
from .libros import views as vl

urlpatterns = [
	path('', cont_index, name='contabilidad'),
	# Asientos
	path('asientos/', include('contabilidad.asientos.urls')),
	# Mayores
	path('mayores/', vl.mayores_index, name='mayores'),
	# Mayores
	path('sys/', vl.sys_index, name='sys'),
	# Ejercicios
	path('ejercicios/', include('contabilidad.ejercicios.urls')),
	# Plan de cuentas
	path('cuentas/', include('contabilidad.cuentas.urls')),
]

contabilidad/asientos/models.py
from django.db import models

# Create your models here.

contabilidad/cuentas/models.py
from django.db import models

# Create your models here.

contabilidad/models.py
from __future__ import unicode_literals
from datetime import date
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from consorcios.models import *


class Cuenta(models.Model):
	consorcio = models.ForeignKey(Consorcio, blank=True, null=True, on_delete=models.CASCADE) # Para cuentas especificas
	nivel = models.IntegerField()
	dependencia = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
	numero = models.CharField(max_length=6)
	nombre = models.CharField(max_length=50)

	def __str__(self):
		nombre = '%s | %s' % (self.numero, self.nombre)
		return nombre


	def operaciones(self, ejercicio, fecha_inicio=None, fecha_fin=None):

		""" Recoje las operaciones """

		if not fecha_inicio:
			fecha_inicio = ejercicio.inicio

		if not fecha_fin:
			fecha_fin = ejercicio.cierre

		return self.operacion_set.filter(
				asiento__fecha_asiento__range=[fecha_inicio, fecha_fin],
				asiento__consorcio=ejercicio.consorcio
			)


	def saldo_debe(self, operaciones):

		""" Saldo del debe, tiene que recibir las operaciones """

		return sum([o.debe for o in operaciones])

	def saldo_haber(self, operaciones):

		""" Saldo del haber, tiene que recibir las operaciones """

		return sum([o.haber for o in operaciones])

	def saldo(self, ejercicio, fecha_inicio=None, fecha_fin=None):

		operaciones = self.operaciones(ejercicio, fecha_inicio=fecha_inicio, fecha_fin=fecha_fin)
		debe = self.saldo_debe(operaciones)
		haber = self.saldo_haber(operaciones)
		numero = int(self.numero) # Numero de la cuenta expresado en int
		if numero in range(100000,199999) or numero > 500000:
			saldo = debe - haber
		else:
			saldo = haber - debe
		return saldo

	class Meta:
		ordering = ['numero']



class Plan(models.Model):
	consorcio = models.ForeignKey(Consorcio, blank=True, null=True, on_delete=models.CASCADE)
	cuentas = models.ManyToManyField(Cuenta)

	def __str__(self):
		nombre = '%s' % (self.consorcio)
		return nombre



class Operacion(models.Model):
	numero_aleatorio = models.CharField(max_length=30, blank=True, null=True)
	cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE)
	debe = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
	haber = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
	descripcion = models.CharField(max_length=150, blank=True, null=True)

	def __str__(self):
		nombre = '%s' % (self.cuenta)
		return nombre


class Asiento(models.Model):
	consorcio = models.ForeignKey(Consorcio, on_delete=models.CASCADE)
	fecha_asiento = models.DateField()
	descripcion = models.CharField(max_length=150, blank=True, null=True)
	fecha_creacion = models.DateField(auto_now_add=True, auto_now=False)
	fecha_ultima_modificacion = models.DateField(auto_now_add=False, auto_now=True)
	operaciones = models.ManyToManyField(Operacion)
	principal = models.IntegerField(blank=True, null=True) # 1 para apertura, 2 para cierre de resultados, 3 para cierre patrimonial

	def __str__(self):
		nombre = '%s' % (self.fecha_asiento)
		return nombre


class Ejercicio(models.Model):
	consorcio = models.ForeignKey(Consorcio, on_delete=models.CASCADE)
	numero_aleatorio = models.CharField(max_length=30)
	nombre = models.CharField(max_length=15)
	inicio = models.DateField()
	cierre = models.DateField()
	activo = models.BooleanField(default=False)

	def __str__(self):
		nombre = '%s' % (self.nombre)
		return nombre

	def save(self, *args, **kw):
		if self.activo == True:
			otros_ejercicios = Ejercicio.objects.filter(consorcio=self.consorcio).exclude(id=self.id)
			if otros_ejercicios:
				otros_ejercicios.update(activo=False)
		super(Ejercicio, self).save(*args, **kw)


	def delete(self, *args, **kw):
		otros_ejercicios = Ejercicio.objects.filter(consorcio=self.consorcio).exclude(id=self.id).order_by('-cierre')
		if otros_ejercicios:
			otros_ejercicios[0].activo = True
			otros_ejercicios[0].save()
		super(Ejercicio, self).delete(*args, **kw)

contabilidad/cuentas/forms.py
from django import forms
from django.forms import Textarea, TextInput, NullBooleanSelect, Select
from contabilidad.models import *

class cuentaForm(forms.ModelForm):
	class Meta:
		model = Cuenta
		fields = ['dependencia', 'numero', 'nombre']
		labels = {
			'dependencia': 'Depende del rubro',
			'numero': 'Numero de cuenta',
			'nombre': 'Nombre de la cuenta',
		}

	def __init__(self, consorcio=None, *args, **kwargs):
		self.consorcio = consorcio
		super(cuentaForm, self).__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
						'class': 'form-control',
				})
		self.fields['dependencia'].queryset = Plan.objects.get(consorcio=consorcio).cuentas.filter(nivel=3).order_by('numero')

contabilidad/asientos/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.views.decorators.http import require_http_methods
from admincu.funciones import *
from consorcios.models import *
from arquitectura.models import *
from contabilidad.models import *
from django_afip.models import *
from .forms import *
from django.forms import modelformset_factory
from django.db import transaction
from .funciones import *

@group_required('contable')
@transaction.atomic
def asiento_index(request, numero=None):
	# Traer ejercicio activo
	try:
		ejercicio = Ejercicio.objects.get(consorcio=consorcio(request), activo=True)
		apropiadorDeAsientosPrincipales(ejercicio)
	except:
		mensaje = "Debe activar un ejercicio para poder realizar un asiento."
		messages.add_message(request, messages.ERROR, mensaje)
		return redirect('contabilidad')

	asientos = Asiento.objects.filter(
				consorcio=consorcio(request),
				fecha_asiento__range=[ejercicio.inicio, ejercicio.cierre]
			).order_by('fecha_asiento', 'id')
	q_asientos = asientos.count()
	if numero:
		# Tomar asiento a modificar
		try:
			asiento_mod = asientos[numero-1]
		except:
			mensaje = "No existe el asiento que desea buscar."
			messages.add_message(request, messages.ERROR, mensaje)
			return redirect('asiento')

		# Projimos
		anterior = numero-1 if numero > 1 else None
		posterior = numero+1 if numero < q_asientos else None
	else:
		asiento_mod = None

		# Projimo
		anterior = q_asientos



	form_asiento = asientoForm(
			data=request.POST or None,
			prefix="asiento",
			instance=asiento_mod if asiento_mod else None
		)

	extra = 4 if not asiento_mod else 0

	queryset = Operacion.objects.none() if not asiento_mod else asiento_mod.operaciones.all().order_by('haber')

	suma_debe, suma_haber = 0, 0
	for op in queryset:
		suma_debe += op.debe
		suma_haber += op.haber

	formset = modelformset_factory(
			Operacion,
			form=operacionForm,
			extra=extra,
			can_delete=True,

		)

	formSetOperaciones = formset(
			form_kwargs={
				'consorcio': consorcio(request),
				'data': request.POST or None,
			},
			prefix="op",
			queryset=queryset
			)

	if request.method == "POST":
		if valid_demo(request.user):
			return redirect('asiento')

		formSetOperaciones.extra = int(request.POST.get('op-TOTAL_FORMS'))
		if form_asiento.is_valid():
			# Validaciones
			errores = []
			# Validacion fecha del asiento
			if not (ejercicio.inicio <= form_asiento.cleaned_data['fecha_asiento'] <= ejercicio.cierre):
				error = "La fecha del asiento no corresponde al ejercicio activo."
				errores.append(error)

			# Validacion para no dejar cargar ni modificar asientos en ejercicios ya cerrados

			if ejercicio.asiento_cierre_pat:
				error = "No se puede cargar ni modificar asientos en ejercicios cerrados."
				errores.append(error)

			operaciones = []
			suma_debe = 0
			suma_haber = 0
			identificacion = randomNumber(Operacion, 'numero_aleatorio')
			for f in formSetOperaciones:
				pre, linea = str(f.prefix).split("-")
				linea = str(int(linea)+1)
				if f.is_valid():
					try:
						cuenta = f.cleaned_data['cuenta']
					except:
						cuenta = None
					if cuenta:
						debe = f.cleaned_data['debe'] or 0
						haber = f.cleaned_data['haber'] or 0
						# Validacion por debe y haber en 0
						if debe == 0 and haber == 0:
							break
						suma_debe += debe
						suma_haber += haber
						descripcion = f.cleaned_data['descripcion'] or ""
						operaciones.append(Operacion(
								numero_aleatorio=identificacion,
								cuenta=cuenta,
								debe=debe,
								haber=haber,
								descripcion=descripcion,
							))
						# Validacion numeros positivos
						if debe < 0 or haber < 0:
							error = "Linea %s: Solo se admiten numeros positivos." % linea
							errores.append(error)
						# Validacion importe en ambos lados
						if debe != 0 and haber != 0:
							error = "Linea %s: No se puede colocar importes en ambos campos (Debe y Haber)." % linea
							errores.append(error)

			# Validacion suma de asiento
			if suma_debe != suma_haber:
				error = "El asiento no cuadra."
				errores.append(error)

			if suma_debe == 0 or suma_haber == 0:
				error = "Debe colocar cuentas y valores en las lineas."
				errores.append(error)

			# Guardado
			if not errores and len(operaciones) >= 2:
				if asiento_mod:
					asiento_mod.operaciones.all().delete()

				# Guarda el asiento
				asiento = form_asiento.save(commit=False)
				asiento.consorcio = consorcio(request)
				Operacion.objects.bulk_create(operaciones)
				asiento.save()
				asiento.operaciones.add(*Operacion.objects.filter(numero_aleatorio=identificacion))


				messages.add_message(request, messages.SUCCESS, "Asiento guardado con exito.")
				return redirect('asiento')


	return render(request, 'contabilidad/asientos/asiento.html', locals())


@require_http_methods('POST')
@group_required('contable')
def asiento_eliminar(request):
	if valid_demo(request.user):
		return redirect('asiento')

	try:
		asiento = Asiento.objects.get(id=request.POST.get('eliminar'))
	except:
		asiento = None

	try:
		ejercicio = Ejercicio.objects.filter(consorcio=consorcio(request), cierre__gte=asiento.fecha_asiento).order_by('cierre')[0]
	except:
		ejercicio = None

	if asiento:
		if asiento.principal:
			# Para saber si tiene asientos principales posteriores
			try:
				asiento_principal_posterior = Asiento.objects.get(
					consorcio=consorcio(request),
					fecha_asiento__range=[ejercicio.inicio, ejercicio.cierre],
					principal__gt=asiento.principal
				)
			except:
				asiento_principal_posterior = None

			if not asiento_principal_posterior:
				try:
					ejercicio_posterior = Ejercicio.objects.filter(consorcio=consorcio(request), inicio__gt=ejercicio.cierre).order_by('inicio')[0]

					asiento_principal_posterior = Asiento.objects.get(
						consorcio=consorcio(request),
						fecha_asiento__range=[ejercicio_posterior.inicio, ejercicio_posterior.cierre],
						principal__isnull=False,
					)
				except:
					asiento_principal_posterior = None

			if not asiento_principal_posterior:
				eliminarAsiento(asiento)
				messages.add_message(request, messages.SUCCESS, "Asiento eliminado con exito.")
				devolucion = redirect('ejercicio_set', ejercicio=ejercicio.numero_aleatorio)
			else:
				messages.add_message(request, messages.ERROR, "No se puede eliminar el asiento porque tiene asientos posteriores vinculados")
				devolucion = redirect('ejercicio_set', ejercicio=ejercicio.numero_aleatorio)

		else:
			eliminarAsiento(asiento)
			messages.add_message(request, messages.SUCCESS, "Asiento eliminado con exito.")
			devolucion = redirect('asiento')
	else:
		devolucion = redirect('asiento')
		messages.add_message(request, messages.ERROR, "Hubo un error al eliminar el asiento. Intentelo de nuevo mas tarde.")

	return devolucion


@require_http_methods('POST')
@group_required('contable')
def asiento_generador_principales(request):
	if valid_demo(request.user):
		return redirect('asiento')

	try:
		operacion = request.POST.get('operacion')
		ejercicio = Ejercicio.objects.get(id=request.POST.get('ejercicio'))
	except:
		return redirect('home')

	# Tipos de asientos principales
	tipo = {
		'asiento_apertura': 1,
		'asiento_cierre_res': 2,
		'asiento_cierre_pat': 3,
	}

	# Para evitar doble submit
	try:
		asiento_principal = Asiento.objects.get(
				consorcio=consorcio(request),
				fecha_asiento__range=[ejercicio.inicio, ejercicio.cierre],
				principal=tipo[operacion]
			)
	except:
		asiento_principal = None

	# Generacion del asiento
	realizacion = eval(operacion)(ejercicio) if not asiento_principal else None

	if realizacion == True:
		messages.add_message(request, messages.SUCCESS, "Asiento generado con exito.")
	else:
		messages.add_message(request, messages.ERROR, realizacion)


	return redirect('ejercicio_set', ejercicio=ejercicio.numero_aleatorio)

def asiento_redireccion(request, id_asiento):
	try:
		ejercicio = Ejercicio.objects.get(consorcio=consorcio(request), activo=True)
	except:
		mensaje = "Debe activar un ejercicio para poder visualizar el asiento."
		messages.add_message(request, messages.ERROR, mensaje)
		return redirect('asiento')
	try:
		asiento = Asiento.objects.get(id=id_asiento)
	except:
		mensaje = "No se pudo encontrar el asiento."
		messages.add_message(request, messages.ERROR, mensaje)
		return redirect('asiento')

	if not ejercicio.inicio <= asiento.fecha_asiento <= ejercicio.cierre:
		mensaje = "El asiento que desea visualizar no corresponde al ejercicio activo."
		messages.add_message(request, messages.ERROR, mensaje)
		return redirect('asiento')

	asientos = asientosNumerados(ejercicio)
	for a in asientos:
		if a.id == asiento.id:
			return redirect('asiento_mod', numero=a.numero)

	return redirect('asiento')

contabilidad/eecc/views.py
from django.shortcuts import render

# Create your views here.

contabilidad/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from admincu.funciones import *
from consorcios.models import *
from arquitectura.models import *
from .models import *
from django_afip.models import *
from .forms import *
from .funciones import *


@group_required('contable')
def adm_index(request):
	return render(request, 'contabilidad/administracion.html', locals())


@group_required('contable')
def cont_index(request):
	try:
		ejercicio = Ejercicio.objects.get(consorcio=consorcio(request), activo=True)
	except:
		ejercicio = None

	if ejercicio:
		asientos = Asiento.objects.filter(
				consorcio=consorcio(request),
				fecha_asiento__range=[ejercicio.inicio, ejercicio.cierre]
			).order_by('fecha_asiento', 'id')

	return render(request, 'contabilidad/index.html', locals())

contabilidad/templates/contabilidad/ejercicios/diario.html
{% extends 'raiz.html' %}
{% load staticfiles %}

{% block titulo %}
  Ejercicio {{ejercicio}} - Libro Diario
{% endblock %}

{% block breadcrum %}
  {% include 'comunes/breadcrum.html' with bpadre="contabilidad" bhijo1="ejercicios" bhijo2="diario" %}
{% endblock %}

{% block header %}
  Ejercicio {{ejercicio}} - Libro Diario
{% endblock %}

{% block contenido %}
  <div class="row">
    <div class="col-md-3 hidden-print">
      {% include 'contabilidad/barra.html' %}
    </div>

    <div class="col-md-9">
      {% if not asientos %}
        {% include 'comunes/alerta.html' with tipo="warning" alerta="El ejercicio aun no tiene asientos" %}
      {% endif %}
      <div class="card-box">
        <div class="row">
          <div class="col-md-12">
            <div class="hidden-print m-t-30 m-b-30">
              <div class="text-right">
                <a href="javascript:window.print()" class="btn btn-primary waves-effect waves-light"><i class="fa fa-print m-r-5"></i> Imprimir</a>
              </div>
            </div>        
            <h3>{{ consorcio.nombre_completo }}</h3>
            <h4>Ejercicio {{ ejercicio }} ({{ejercicio.inicio|date:"d/m/Y"}} - {{ejercicio.cierre|date:"d/m/Y"}})</h4>
            <h5>Libro diario</h5>
            <div class="table-responsive">
              {% include 'contabilidad/ejercicios/tabla-diario.html' %}
            </div>

          </div>
        </div>
      </div>
    </div>   

  </div>
{% endblock %}

contabilidad/templates/contabilidad/ejercicios/index.html
{% extends 'raiz.html' %}
{% load staticfiles %}

{% block titulo %}
  Ejercicios contables
{% endblock %}

{% block breadcrum %}
  {% include 'comunes/breadcrum.html' with bpadre="contabilidad" bhijo1="ejercicios" %}
{% endblock %}

{% block header %}
  Ejercicios contables
{% endblock %}

{% block contenido %}
<div class="row">
  <div class="col-md-3">
    {% include 'contabilidad/barra.html' %}
  </div>

  <div class="col-md-9">

    <div class="panel panel-border panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Ejercicios contables</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12">
            <a href="{% url 'ejercicio_nuevo' %}" class="btn btn-info pull-right">
              <i class="fa fa-plus"></i> Nuevo ejercicio
            </a>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsive">
              {% include 'contabilidad/ejercicios/tabla.html' %}
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>
{% endblock %}

contabilidad/templates/contabilidad/ejercicios/nuevo.html
{% extends 'raiz.html' %}
{% load staticfiles %}

{% block titulo %}
  Nuevo ejercicio contable
{% endblock %}

{% block css %}
  <link rel="stylesheet" href='{% static "plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}'>
{% endblock %}

{% block breadcrum %}
  {% include 'comunes/breadcrum.html' with bpadre="contabilidad" bhijo1="ejercicios" bhijo2="nuevo" %}
{% endblock %}

{% block header %}
  Nuevo ejercicio contable
{% endblock %}

{% block contenido %}
	<div class="row">
    <div class="col-md-3">
      {% include 'contabilidad/barra.html' %}
    </div>
		<div class="col-md-6">
  		{% include 'comunes/simple-form.html' %}
		</div>
	</div>
{% endblock %}

{% block js %}
  <script src='{% static "plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}'></script>
  <script src='{% static "anopa/bootstrap-datepicker.es.js" %}'></script>  
  <script>
    $(function () {
      $('#id_inicio').datepicker({
        format: "dd/mm/yyyy",
        autoclose: true,
        orientation: 'bottom auto',
        language: 'es',
      });
      $('#id_cierre').datepicker({
        format: "dd/mm/yyyy",
        autoclose: true,
        orientation: 'bottom auto',
        language: 'es',
      });      
    })
  </script>
{% endblock %}

contabilidad/templates/contabilidad/ejercicios/tabla-diario.html
{% load humanize %}
<table id="anopa" class="anopa table table-condensed">
  <thead>
    <tr>
      <th>N°</th>
      <th>Cuenta</th>
      <th>Debe</th>
      <th>Haber</th>
      <th>Desc</th>
    </tr>
  </thead>
  <tbody>
    {% for asiento in asientos %}
      <tr>
        <td colspan="5" class="text-center info">
          <a href="{% if ejercicio.activo %}{% url 'asiento_mod' numero=forloop.counter %}{% else %}#{% endif %}">
            <small>
              -- Asiento n° {{ forloop.counter }} - Fecha {{ asiento.fecha_asiento|date:"d/m/Y" }} -- 
            </small>
          </a>          
        </td>
      </tr>
      {% for op in asiento.operaciones.all|dictsort:"haber" %}
        <tr>
          <td>{{ op.cuenta.numero }}</td>
          <td>{{ op.cuenta.nombre }}</td>
          <td>{{ op.debe|intcomma }}</td>
          <td>{{ op.haber|intcomma }}</td>
          <td>{{ op.descripcion }}</td>
        </tr>
      {% endfor %}
      <tr>
        <td colspan="5" class="text-center"><i>*
          {% if asiento.descripcion %}
            {{asiento.descripcion}}
          {% else %}
            S/C
          {% endif %}
        </i></td>
      </tr>      
    {% endfor %}
  </tbody>
</table>

contabilidad/templates/contabilidad/ejercicios/tabla.html
{% load staticfiles %}
{% load humanize %}
<table id="anopa" class="table">
  <thead>
    <tr>
      <th width="20"></th>
      <th>Nombre</th>
      <th>Inicio</th>
      <th>Cierre</th>
    </tr>
  </thead>
  <tbody>
    {% for ejercicio in ejercicios %}
      <tr>
        <td class="text-center">
          <a href="{% url 'ejercicio_set' ejercicio=ejercicio.numero_aleatorio %}" class="btn btn-icon btn-bordered btn-purple btn-xs">
            <i class="fa fa-eye"></i>
          </a>
        </td>
        <td>{{ ejercicio.nombre }}</td>
        <td>{{ ejercicio.inicio|date:"d/m/Y" }}</td>
        <td>{{ ejercicio.cierre|date:"d/m/Y" }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>